/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RealTime {
        "resolution": "y"|"M"|"d"|"h"|"m"|"s";
    }
    interface TabComponent {
        "activeTab": number;
        "tabCnt": number;
    }
}
declare global {
    interface HTMLRealTimeElement extends Components.RealTime, HTMLStencilElement {
    }
    var HTMLRealTimeElement: {
        prototype: HTMLRealTimeElement;
        new (): HTMLRealTimeElement;
    };
    interface HTMLTabComponentElement extends Components.TabComponent, HTMLStencilElement {
    }
    var HTMLTabComponentElement: {
        prototype: HTMLTabComponentElement;
        new (): HTMLTabComponentElement;
    };
    interface HTMLElementTagNameMap {
        "real-time": HTMLRealTimeElement;
        "tab-component": HTMLTabComponentElement;
    }
}
declare namespace LocalJSX {
    interface RealTime {
        "resolution"?: "y"|"M"|"d"|"h"|"m"|"s";
    }
    interface TabComponent {
        "activeTab"?: number;
        "tabCnt"?: number;
    }
    interface IntrinsicElements {
        "real-time": RealTime;
        "tab-component": TabComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "real-time": LocalJSX.RealTime & JSXBase.HTMLAttributes<HTMLRealTimeElement>;
            "tab-component": LocalJSX.TabComponent & JSXBase.HTMLAttributes<HTMLTabComponentElement>;
        }
    }
}
